routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\File;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::any('ulogin','SocialController@ulogin');

Route::get('user','UserController@index')->name('user.index');

Route::get('user/{id}', 'UserController@show')->name('user.show');

Route::get('settings', 'UserController@settings')->name('settings');;

Route::put('settings/update', 'UserController@update');

Route::get('medal','UserController@medal')->name('medal');
Route::post('medalStore','UserController@medalStore')->name('medalStore');

Route::get('policy','UserController@policy')->name('policy');

//Route::get('images/{filename}', function ($filename)
//{
//    $path = storage_path('app\users\\' . $filename);
//
//    if (!File::exists($path)) {
//        abort(404);
//    }
//
//    $file = File::get($path);
//    $type = File::mimeType($path);
//
//    $response = Response::make($file, 200);
//    $response->header("Content-Type", $type);
//
//    return $response;
//});


//Route::get('marathon','MarathonController@index');
//Route::get('marathon/{id}', 'MarathonController@show')->name('marathon.show');
Route::resource('marathon', 'MarathonController');
Route::get('marathon/{id}/join','MarathonController@join')->name('marathon.join');
Route::get('marathon/{id}/markDay','MarathonController@markDay')->name('marathon.markDay');
Route::get('marathon/{id}/control','MarathonController@control')->name('marathon.control');
Route::post('marathon/{id}/kick','MarathonController@kick')->name('marathon.kick');
Route::post('marathon_add_comment','MarathonController@addComment');
Route::get('marathon_edit_comment/{id}','MarathonController@editComment')->name('marathon_edit_comment');
Route::post('marathon_edit_comment_update/{id}','MarathonController@editCommentUpdate')->name('marathon_edit_comment_update');

//Route::resource('post', 'PostController');
//Route::post('post_add_comment','PostController@addComment');

app/Models/Marathon.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;

class Marathon extends Model
{
    const MARATHON_STATUS_PENDING = 0;
    const MARATHON_STATUS_REG = 1;
    const MARATHON_STATUS_ACTIVE = 2;
    const MARATHON_STATUS_FINISH = 3;

    public static $status_names = [
        self::MARATHON_STATUS_PENDING => 'Запись скоро начнется',
        self::MARATHON_STATUS_REG => 'Идет запись',
        self::MARATHON_STATUS_ACTIVE => 'В процессе',
        self::MARATHON_STATUS_FINISH => 'Завершен',
    ];

    protected $fillable = [
        'title', 'description', 'rules', 'tips', 'auto_kick_days', 'repeat_type', 'weekends', 'start_at', 'end_at', 'reg_start_at', 'reg_end_at', 'image',
    ];

    protected $dates = ['start_at', 'end_at', 'reg_start_at', 'reg_end_at'];

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_marathon')
            ->withPivot('status');
    }

    public function activeUsers()
    {
        return $this->belongsToMany(User::class, 'user_marathon')
            ->where('status', '=', 1)
            ->withPivot('status');;
    }

    public function comments()
    {
        return $this->hasMany(MarathonComment::class)
            ->orderBy('created_at', 'desc');
    }

    public function isUserMember($user_id)
    {
        $is_exist = UserMarathon::where('user_id', $user_id)
            ->where('marathon_id', $this->id)
            ->where('status', 1)
            ->exists();

        return $is_exist;
    }

    public function markDay($user_id, $time = null)
    {
        $time = isset($time) ? $time : time();
        $day = date('Y-m-d 00:00:00', $time);

        if ($this->isUserMember($user_id)) {
            if (!$this->isMarkedToday($user_id)) {
                MarathonMark::create([
                    'marathon_id' => $this->id,
                    'user_id' => $user_id,
                    'check_date' => $day,
                ]);
            }
        }
    }

    public function getUserMarks($user_id)
    {
        $marks = MarathonMark::where('user_id', $user_id)
            ->where('marathon_id', $this->id)
            ->get();

        return $marks;
    }

    public function getUserMarksForGraph($user_id)
    {
        $marks = MarathonMark::where('user_id', $user_id)
            ->where('marathon_id', $this->id)
            ->get();
        $graph = [];
        /* create grid of dates */
        $duration = $this->getDurationDays();
        $start_date = $this->start_at->format('d.m.Y');

        for ($day = 1; $day <= $duration; $day++) {
            $graph[$start_date] = ['num' => $day, 'success' => false, 'today' => false];
            $start_date = date('d.m.Y', strtotime("+1 day", strtotime($start_date)));
        }

        foreach ($marks as $mark) {
            if (array_key_exists($mark->check_date->format('d.m.Y'), $graph)) {
                $graph[$mark->check_date->format('d.m.Y')]['success'] = true;
            }
        }

        $today = date('d.m.Y', time());
        if (array_key_exists($today, $graph)) {
            $graph[$today]['today'] = true;
        }

        return $graph;
    }

    public function isMarkedToday($user_id)
    {
        $time = time();
        $from = date('Y-m-d 00:00:00', $time);
        $to = date('Y-m-d 23:59:59', $time);
        $is_exist = MarathonMark::where('user_id', $user_id)
            ->where('check_date', '>=', $from)
            ->where('check_date', '<=', $to)
            ->where('marathon_id', $this->id)
            ->exists();

        return $is_exist;
    }

    public function joinMember($user_id)
    {
        $reg = new UserMarathon();
        $reg->marathon_id = $this->id;
        $reg->user_id = $user_id;
        $reg->status = 1;
        $reg->save();
    }

    public function cancelMember($user_id)
    {
        UserMarathon::where('user_id', $user_id)
            ->update(['status' => 0]);
    }

    public function kickMember($user_id)
    {
        UserMarathon::where('user_id', $user_id)
            ->update(['status' => 2]);
    }

    public function returnMember($user_id)
    {
        UserMarathon::where('user_id', $user_id)
            ->where('status', 2)
            ->update(['status' => 1]);
    }

    public function getStatus()
    {
        $status = self::MARATHON_STATUS_PENDING;
        $now = time();
        if ($now < strtotime($this->reg_start_at)) {
            $status = self::MARATHON_STATUS_PENDING;
        } elseif ($now > strtotime($this->reg_start_at) and $now < strtotime($this->start_at)) {
            $status = self::MARATHON_STATUS_REG;
        } elseif ($now > strtotime($this->start_at) and $now < strtotime($this->end_at)) {
            $status = self::MARATHON_STATUS_ACTIVE;
        } elseif ($now > strtotime($this->end_at)) {
            $status = self::MARATHON_STATUS_FINISH;
        }
        return $status;
    }

    public function getDurationDays()
    {
        $days = Carbon::parse($this->start_at)->diffInDays(Carbon::parse($this->end_at));
        return $days;
    }

    public function getStatusName()
    {
        return self::$status_names[$this->getStatus()];
    }
}

app/Http/Controllers/MarathonController.php
<?php

namespace App\Http\Controllers;

use App\Models\Marathon;
use App\Models\MarathonComment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MarathonController extends Controller
{
    public function __construct(Marathon $marathon, MarathonComment $comment)
    {
        $this->marathon = $marathon;
        $this->comment = $comment;
    }

    public function index()
    {
        $marathons = $this->marathon->latest()->where('is_deleted', '=', 0)->paginate(6);

        return view('marathon.index',
            ['marathons' => $marathons]
        );
    }

    public function show($id)
    {
        $marathon = $this->marathon::findOrFail($id);
        $comments = $marathon->comments()->latest()->paginate(10);
        $marks = false;
        if (Auth::check()){
            $marks = $marathon->getUserMarksForGraph(Auth::id());
        }

        return view('marathon.show',
            [
                'comments' => $comments,
                'marathon' => $marathon,
                'status' => $marathon->getStatus(),
                'marks' => $marks,
            ]
        );
    }

    public function create()
    {
        if (!Auth::user()->isModer()) {
            abort(404);
        }
        return view('marathon.create');
    }

    public function store(Request $request)
    {
        if (!Auth::user()->isModer()) {
            abort(404);
        }
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'rules' => 'required',
            'auto_kick_days' => 'integer',
            'repeat_type' => 'integer',
            'weekends' => 'required|integer',
            'start_at' => 'required|date',
            'end_at' => 'required|date',
            'reg_start_at' => 'required|date',
            'reg_end_at' => 'required|date',
            'image' => 'required',
        ]);

        $data = $request->all();

        if ($request->hasFile('image') && $request->file('image')->isValid()) {
            $name = time() . "_marathon_image";
            $extension = $request->image->extension();
            $nameImage = "{$name}.$extension";
            $data['image'] = $nameImage;

            $upload = $request->image->storeAs('public/uploads/images/marathon', $nameImage);
            if (!$upload)
                return redirect()
                    ->back()
                    ->with('errors', ['Ошибка загрузки файла'])
                    ->withInput();
        }

        $this->marathon::create($data);

        return redirect()
            ->route('marathon.index');
    }

    public function edit($id)
    {
        if (!Auth::user()->isModer()) {
            abort(404);
        }
        if (!$marathon = $this->marathon->find($id))
            return redirect()->back();

        return view('marathon.edit', compact('marathon'));
    }

    public function update(Request $request, $id)
    {
        if (!Auth::user()->isModer()) {
            abort(404);
        }
        if (!$marathon = $this->marathon->find($id))
            return redirect()->back();

        $data = $request->all();

        if ($request->hasFile('image') && $request->file('image')->isValid()) {
            $name = time() . "_marathon_image";
            $extension = $request->image->extension();
            $nameImage = "{$name}.$extension";
            $data['image'] = $nameImage;

            $upload = $request->image->storeAs('public/uploads/images/marathon', $nameImage);

            if (!$upload)
                return redirect()
                    ->back()
                    ->with('errors', ['Ошибка загрузки файла'])
                    ->withInput();
        }

        $marathon->update($data);

        return redirect()
            ->route('marathon.index');
    }

    public function destroy($id)
    {
        if (!Auth::user()->isModer()) {
            abort(404);
        }
        if (!$marathon = $this->marathon->find($id))
            return redirect()->back();

        $marathon->delete();

        return redirect()
            ->route('marathon.index');
    }

    public function addComment(Request $request)
    {
        if (!Auth::check()) return redirect('');
        $request->validate([
            'body' => 'required',
            'marathon_id' => 'required',
        ]);

        $marathon = $this->marathon::findOrFail($request->marathon_id);

        MarathonComment::create([
            'body' => $request->body,
            'user_id' => Auth::id(),
            'marathon_id' => $marathon->id
        ]);

        return redirect()->route('marathon.show', $marathon->id);
    }

    public function editComment($id)
    {
        $comment = $this->comment->find($id);
        if (!Auth::check() or !$comment) return redirect()->back();
        if (Auth::id() != $comment->user_id and !Auth::user()->isModer()) return redirect()->back();

        return view('marathon.edit_comment', compact('comment'));
    }

    public function editCommentUpdate(Request $request, $id)
    {
        $comment = $this->comment->find($request->id);
        if (!Auth::check() or !$comment) return redirect()->back();
        if (Auth::id() != $comment->user_id and !Auth::user()->isModer()) return redirect()->back();
        $request->validate([
            'body' => 'required',
        ]);
        $comment->update($request->all());

        return redirect()->route('marathon.show', $comment->marathon_id);
    }

    public function join($id)
    {
        $marathon = $this->marathon->find($id);
        if (!Auth::check() or !$marathon) return redirect()->back();

        $is_member = $marathon->isUserMember(Auth::id());

        if ($is_member) {
            $marathon->cancelMember(Auth::id());
        } else {
            $marathon->joinMember(Auth::id());
        }

        return redirect()->route('marathon.show', $marathon->id);
    }

    public function markDay($id)
    {
        $marathon = $this->marathon->find($id);
        if (!Auth::check() or !$marathon) return redirect()->back();

        $is_member = $marathon->isUserMember(Auth::id());

        if ($is_member) {
            $marathon->markDay(Auth::id());
        }

        return redirect()->route('marathon.show', $marathon->id);
    }

    public function control($id)
    {
        if (!Auth::user()->isModer()) {
            abort(404);
        }
        $marathon = $this->marathon::findOrFail($id);
        return view('marathon.control',
            [
                'marathon' => $marathon,
            ]
        );
    }

    public function kick(Request $request, $id)
    {
        if (!Auth::user()->isModer()) {
            abort(404);
        }
        $user_id = $request->user_id;
        if (!$marathon = $this->marathon->find($id) or !$user_id)
            return redirect()->back();
        $status = 'unknown';
        if ($marathon->isUserMember($user_id)) {
            $marathon->kickMember($user_id);
            $status = 'kicked';
        } else {
            $marathon->returnMember($user_id);
            $status = 'joined';
        }
        return response()->json(['status' => $status]);
    }
}

resources/views/marathon/control.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header lead">{{ $marathon->title }}</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">ID</th>
                                        <th scope="col">Имя</th>
                                        <th scope="col">Статус</th>
                                        <th scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($marathon->users as $user)
                                        <tr>
                                            <th scope="row">{{ $user->id }}</th>
                                            <td>{{ $user->name }}</td>
                                            <td>
                                                @if ($user->pivot->status == 1)
                                                    Активный
                                                @elseif ($user->pivot->status == 2)
                                                    Вылетел
                                                @else
                                                    Отменил заявку
                                                @endif
                                            </td>
                                            <td>
                                                @if ($user->pivot->status == 1)
                                                    <button class="btn btn-danger btn-sm return-member" data-user_id="{{ $user->id }}">Кикнуть</button>
                                                @elseif ($user->pivot->status == 2)
                                                    <button class="btn btn-secondary btn-sm return-member" data-user_id="{{ $user->id }}">Вернуть</button>
                                                @endif
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <script>
        // вернуть участника
        $(document).on('click', '.return-member', function(){
            var user_id = $(this).data('user_id');

            $.ajax({
                type: 'POST',
                url: '{{ route('marathon.kick', $marathon->id) }}',
                data: { user_id: user_id, _token: '{{ csrf_token() }}'},
                success: function(data){
                    location.reload();
                }
            });

        });
    </script>
@endsection

resources/views/marathon/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header lead">Создать марафон</div>

                    <div class="card-body">


                        <form action="{{ route('marathon.store') }}" method="post" enctype="multipart/form-data">
                            @include('parts.alerts')
                            @csrf

                            <div class="form-group">
                                <input value="{{ $marathon->title ?? old('title') }}" class="form-control" type="text" name="title" placeholder="Название">
                            </div>
                            <div class="form-group">
                                <label for="image">Картинка</label>
                                <input class="form-control" type="file" name="image">
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="description" cols="30" rows="5" placeholder="Описание">{{ $marathon->description ?? old('description') }}</textarea>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="rules" cols="30" rows="5" placeholder="Правила">{{ $marathon->rules ?? old('rules') }}</textarea>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="tips" cols="30" rows="5" placeholder="Полезная информация">{{ $marathon->tips ?? old('tips') }}</textarea>
                            </div>
                            <div class="form-group">
                                <input value="{{ $marathon->auto_kick_days ?? old('auto_kick_days') }}" class="form-control" type="number" name="auto_kick_days" placeholder="Автокик через n-дней" min="0">
                            </div>
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text">Тип марафона</label>
                                    </div>
                                    <select name="repeat_type" class="custom-select">
                                        <option selected value="0">Ежедневный</option>
                                        <option value="1">Дней в неделю</option>
                                        <option value="2">Специальный</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <input value="{{ $marathon->weekends ?? old('weekends') }}" class="form-control" type="number" name="weekends" placeholder="Кол-во выходных дней" min="0">
                            </div>
                            <div class='form-group'>
                                <label>Дата начала марафона</label>
                                <input value="{{ $marathon->start_at ?? old('start_at') }}" class="form-control" type="date" name="start_at">
                            </div>
                            <div class='form-group'>
                                <label>Дата окончания марафона</label>
                                <input value="{{ $marathon->end_at ?? old('end_at') }}" class="form-control" type="date" name="end_at">
                            </div>
                            <div class='form-group'>
                                <label>Дата начала регистрации</label>
                                <input value="{{ $marathon->reg_start_at ?? old('reg_start_at') }}" class="form-control" type="date" name="reg_start_at">
                            </div>
                            <div class='form-group'>
                                <label>Дата окончания регистрации</label>
                                <input value="{{ $marathon->reg_end_at ?? old('reg_end_at') }}" class="form-control" type="date" name="reg_end_at">
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Создать</button>
                            </div>

                        </form>




                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/marathon/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header lead">Редактировать марафон #{{$marathon->id}}</div>
                    <div class="card-body">
                        <form action="{{ route('marathon.update', $marathon->id) }}" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="_method" value="PUT">

                            @include('parts.alerts')
                            @csrf
                            <div class="form-group">
                                <input value="{{ $marathon->title ?? old('title') }}" class="form-control" type="text" name="title" placeholder="Название">
                            </div>
                            <div class="form-group">
                                <label for="image">Картинка</label>
                                <input class="form-control" type="file" name="image">
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="description" cols="30" rows="5" placeholder="Описание">{{ $marathon->description ?? old('description') }}</textarea>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="rules" cols="30" rows="5" placeholder="Правила">{{ $marathon->rules ?? old('rules') }}</textarea>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="tips" cols="30" rows="5" placeholder="Полезная информация">{{ $marathon->tips ?? old('tips') }}</textarea>
                            </div>
                            <div class="form-group">
                                <input value="{{ $marathon->auto_kick_days ?? old('auto_kick_days') }}" class="form-control" type="number" name="auto_kick_days" placeholder="Автокик через n-дней" min="0">
                            </div>

                            <div class="form-group">
                                <input value="{{ $marathon->weekends ?? old('weekends') }}" class="form-control" type="number" name="weekends" placeholder="Кол-во выходных дней" min="0">
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/marathon/edit_comment.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header lead">Редактировать комментарий</div>

                    <div class="card-body">
                        <form action="{{ route('marathon_edit_comment_update', $comment->id) }}" method="post" enctype="multipart/form-data">
                            @include('parts.alerts')
                            @csrf
                            <div class="form-group">
                                <textarea class="form-control" name="body" cols="30" rows="5" placeholder="Содержание">{{ $comment->body ?? old('body') }}</textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/marathon/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Марафоны</h1>
            </div>
            <div class="col-md-12">
                <p class="lead">
                    Записывайся на марафоны и приобретай новые полезные привычки вместе с другими участниками!
                </p>
            </div>
        </div>

        <div class="row">
            @foreach ($marathons as $marathon)
            <div class="col-md-4 mb-3 marathon-item">
                <div class="card">
                    <div class="marathon-days-badge"><div class="marathon-days-badge-count">{{ $marathon->getDurationDays() }}</div>дней</div>
                    <img class="card-img-top" src="{{url("storage/uploads/images/marathon/".$marathon->image)}}">
                    <div class="card-body">
                        <h5 class="card-title text-center"><a href="{{ route('marathon.show', $marathon->id) }}">{{ $marathon->title }}</a></h5>
                        <p class="card-text text-truncate text-center">{{ $marathon->description }}</p>
                    </div>
                    <div class="marathon-status-badge"><span class="badge">{{ $marathon->getStatusName() }}</span></div>
                </div>
            </div>
            @endforeach

        </div>

       {{ $marathons->render() }}
    </div>
@endsection