routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\File;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::any('ulogin','SocialController@ulogin');

Route::get('user','UserController@index')->name('user.index');

Route::get('user/{id}', 'UserController@show')->name('user.show');

Route::get('settings', 'UserController@settings')->name('settings');;

Route::put('settings/update', 'UserController@update');

Route::get('medal','UserController@medal')->name('medal');
Route::post('medalStore','UserController@medalStore')->name('medalStore');

Route::get('policy','UserController@policy')->name('policy');

//Route::get('images/{filename}', function ($filename)
//{
//    $path = storage_path('app\users\\' . $filename);
//
//    if (!File::exists($path)) {
//        abort(404);
//    }
//
//    $file = File::get($path);
//    $type = File::mimeType($path);
//
//    $response = Response::make($file, 200);
//    $response->header("Content-Type", $type);
//
//    return $response;
//});


//Route::get('marathon','MarathonController@index');
//Route::get('marathon/{id}', 'MarathonController@show')->name('marathon.show');
Route::resource('marathon', 'MarathonController');
Route::get('marathon/{id}/join','MarathonController@join')->name('marathon.join');
Route::get('marathon/{id}/markDay','MarathonController@markDay')->name('marathon.markDay');
Route::get('marathon/{id}/control','MarathonController@control')->name('marathon.control');
Route::post('marathon/{id}/kick','MarathonController@kick')->name('marathon.kick');
Route::post('marathon_add_comment','MarathonController@addComment');
Route::get('marathon_edit_comment/{id}','MarathonController@editComment')->name('marathon_edit_comment');
Route::post('marathon_edit_comment_update/{id}','MarathonController@editCommentUpdate')->name('marathon_edit_comment_update');

//Route::resource('post', 'PostController');
//Route::post('post_add_comment','PostController@addComment');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/images/logo_32.png" type="image/x-icon">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>From Monday - марафоны полезных привычек</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="{{ asset('js/tooltipster.bundle.min.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Rubik+Mono+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Russo+One&display=swap" rel="stylesheet">


    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
    <link href="{{ asset('css/tooltipster.bundle.min.css') }}" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">


    <script src="//code.jivosite.com/widget.js" jv-id="rEAhei5avE" async></script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <div class="container">
                <a href="{{ route('marathon.index') }}">
                    <div class="navbar-logo"></div>
                </a>

                <a class="navbar-brand mb-0 h1" href="{{ route('marathon.index') }}">
                    From Monday
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('marathon.index') }}">Марафоны</a>
                        </li>
                        {{--<li class="nav-item">--}}
                            {{--<a class="nav-link" href="{{ route('post.index') }}">Посты</a>--}}
                        {{--</li>--}}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('user.index') }}">Люди</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" target="_blank" href="https://vk.com/frommondayru">Вконтакте</a>
                        </li>

                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">Вход</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">Регистрация</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('user.show', Auth::id()) }}">Мой профиль</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Выход
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @include('parts.yandex')

    <footer class="page-footer">
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            <ul class="list-unstyled">
                <li>
                    <a href="{{ route('policy') }}">Политика конфиденциальности</a>
                </li>
            </ul>
            © 2019 Copyright:
            <a href="https://frommonday.ru">FromMonday.ru</a>
        </div>
        <!-- Copyright -->
    </footer>
</body>
</html>